export const WELCOME_EMAIL_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <meta name="x-apple-disable-message-reformatting">
    <title>Welcome to Dapp Trading Assistant</title>
</head>

<body style="margin: 0; padding: 0; background-color: #050505; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
    <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="background-color: #050505;">
        <tr>
            <td align="center" class="mobile-outer-padding" style="padding: 40px 20px;">
                <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" class="email-container" style="max-width: 600px; background-color: #141414; border-radius: 8px; border: 1px solid #30333A;">
                    
                    <!-- Header with Logo -->
                    <tr>
                        <td align="left" class="mobile-header-padding" style="padding: 40px 40px 20px 40px;">
                            <img src="https://res.cloudinary.com/dnlllum6x/image/upload/v1769701128/logo_k4zkma.png" alt="App Logo" width="150" style="max-width: 100%; height: auto;">
                        </td>
                    </tr>
                    
                    <!-- Dashboard Preview Image -->
                    <tr>
                        <td align="center" class="dashboard-preview" style="padding: 40px 40px 0px 40px;">
                            <img src="https://res.cloudinary.com/dnlllum6x/image/upload/v1769701128/market-dashboard_tgqodt.png" alt="Dashboard Preview" width="100%" style="max-width: 520px; width: 100%; height: auto; border-radius: 12px; border: 1px solid #30333A;">
                        </td>
                    </tr>
                    
                    <!-- Main Content -->
                    <tr>
                        <td class="mobile-padding" style="padding: 40px 40px 40px 40px;">
                            
                            <!-- Welcome Heading -->
                            <h1 class="mobile-title dark-text" style="margin: 0 0 30px 0; font-size: 24px; font-weight: 600; color: #FDD458; line-height: 1.2;">
                                Welcome aboard {{name}}
                            </h1>
                            
                            <!-- Intro Text generated by Gemini -->
                            <div style="margin-bottom: 20px;">
                                {{intro}}
                            </div>

                            <!-- CTA Button -->
                            <table role="presentation" cellspacing="0" cellpadding="0" border="0" style="margin: 0 0 40px 0; width: 100%;">
                                <tr>
                                    <td align="center">
                                        <a href="{{url}}" style="display: block; width: 100%; background: linear-gradient(135deg, #FDD458 0%, #E8BA40 100%); color: #000000; text-decoration: none; padding: 16px 32px; border-radius: 8px; font-size: 16px; font-weight: 500; line-height: 1; text-align: center; box-sizing: border-box;">
                                            Go to Dashboard
                                        </a>
                                    </td>
                                </tr>
                            </table>
                            
                            <!-- Footer Text -->
                            <p class="mobile-text dark-text-muted" style="margin: 40px 0 0 0; font-size: 14px; line-height: 1.5; color: #CCDADC !important; text-align: center;">
                                © 2026  DApp Trading Assistant
                            </p>
                        </td>
                    </tr>
                    
                </table>
            </td>
        </tr>
    </table>
</body>
</html>`;

export const RESET_PASSWORD_EMAIL_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <meta name="x-apple-disable-message-reformatting">
    <title>Reset your password</title>

<style>
@media (prefers-color-scheme: dark) {
  body { background-color:#0a0e27 !important; }
  .card { background-color:#141d35 !important; border-color:#1e3a5f !important; }
  .title, .text { color:#f0f4f8 !important; }
  .muted { color:#cbd5e1 !important; }
}
</style>
</head>

<body style="margin:0;padding:0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<table width="100%">
<tr>
<td align="center" style="padding:40px 16px;">

<table class="card" width="100%" style="max-width:620px;background:#ffffff;border-radius:10px;border:1px solid #e2e8f0;overflow:hidden;">

<!-- Header -->
<tr>
<td style="padding:28px 32px;">
<img src="https://res.cloudinary.com/dnlllum6x/image/upload/v1769701128/logo_k4zkma.png"
     width="140" alt="App logo" />
</td>
</tr>

<!-- Dashboard image -->
<tr>
<td>
<img src="https://res.cloudinary.com/dnlllum6x/image/upload/v1769701128/market-dashboard_tgqodt.png"
     width="100%" alt="Dashboard preview"
     style="display:block;border-top:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0;" />
</td>
</tr>

<!-- Content -->
<tr>
<td style="padding:32px;">
<h1 class="title" style="margin:0 0 12px;font-size:22px;color:#0a0e27;">
Reset your password
</h1>

<p class="text" style="margin:0 0 20px;font-size:15px;line-height:1.6;color:#475569;">
Hi {{name}},<br><br>
We received a request to reset your password.
Click the button below to continue.
</p>

<a href="{{url}}"
style="display:block;background:#3b82f6;color:#ffffff;text-decoration:none;
padding:14px 18px;border-radius:8px;text-align:center;font-size:15px;">
Reset password
</a>

<p class="muted" style="margin-top:18px;font-size:13px;color:#475569;">
This link expires in {{expiresIn}}.<br>
If you didn’t request this, you can ignore this email.
</p>
</td>
</tr>

</table>

</td>
</tr>
</table>
</body>
</html>`;

export const VERIFY_EMAIL_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Verify your email</title>

<style>
@media (prefers-color-scheme: dark) {
  body { background-color:#0a0e27 !important; }
  .card { background-color:#141d35 !important; border-color:#1e3a5f !important; }
  .title, .text { color:#f0f4f8 !important; }
  .muted { color:#cbd5e1 !important; }
}
</style>
</head>

<body style="margin:0;padding:0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<table width="100%">
<tr>
<td align="center" style="padding:40px 16px;">

<table class="card" width="100%" style="max-width:620px;background:#ffffff;border-radius:10px;border:1px solid #e2e8f0;overflow:hidden;">

<!-- Header -->
<tr>
<td style="padding:28px 32px;">
<img src="https://res.cloudinary.com/dnlllum6x/image/upload/v1769701128/logo_k4zkma.png"
     width="140" alt="App logo" />
</td>
</tr>

<!-- Dashboard image -->
<tr>
<td>
<img src="https://res.cloudinary.com/dnlllum6x/image/upload/v1769701128/market-dashboard_tgqodt.png"
     width="100%" alt="Dashboard preview"
     style="display:block;border-top:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0;" />
</td>
</tr>

<!-- Content -->
<tr>
<td style="padding:32px;">
<h1 class="title" style="margin:0 0 12px;font-size:22px;color:#0a0e27;">
Verify your email
</h1>

<p class="text" style="margin:0 0 20px;font-size:15px;line-height:1.6;color:#475569;">
Hi {{name}},<br><br>
Please confirm your email address to activate your account.
</p>

<a href="{{url}}"
style="display:block;background:#3b82f6;color:#ffffff;text-decoration:none;
padding:14px 18px;border-radius:8px;text-align:center;font-size:15px;">
Verify email
</a>

<p class="muted" style="margin-top:18px;font-size:13px;color:#475569;">
If you didn’t create this account, you can safely ignore this email.
</p>
</td>
</tr>

</table>

</td>
</tr>
</table>
</body>
</html>`;
